### ISSUE TITLE
Instellen mislukt, wordt opnieuw geprobeerd

### ISSUE THREAD

**Issue by Mickeyr61** [bajansen/home-assistant-frank_energie#101]
Thanks for the great Frank Energy plugin! I have installed the plugin using the documentatie. Everything went fine, exempt for fetching the data. I am stuck with the above error and no devices or entities are installed. I enabled the log and it says:

`2024-02-14 12:22:07.977 DEBUG (MainThread) [custom_components.frank_energie.coordinator] Fetching Frank Energie data
2024-02-14 12:22:08.384 INFO (MainThread) [custom_components.frank_energie.coordinator] No gas prices found for user, falling back to public prices
2024-02-14 12:22:08.384 INFO (MainThread) [custom_components.frank_energie.coordinator] No electricity prices found for user, falling back to public prices
2024-02-14 12:22:08.473 DEBUG (MainThread) [custom_components.frank_energie.coordinator] Finished fetching Frank Energie coordinator data in 0.497 seconds (success: False)`

Maybe it is a password error? Where is the username and password stored?

**Comment by Mickeyr61** [comment]
I tried without login in. This works and created 17 entities.

**Comment by VlarpNL** [comment]
I have the same issue, however, I've been a customer for a couple of years. So that shouldn't be the problem. If I add the integration without logging in at Frank then it's fine, it adds all sensors etc. When I login then the integration gives a "failed setup, will retry" error and no sensors are added to HA.

I'm not getting any apparent error in the logs as far as I can see.

**Comment by AbeltjeNL** [comment]
Data URL:
'''https://frank-graphql-prod.graphcdn.app/

**Comment by twoenter** [comment]
Same issue here!

**Comment by solid-pixel** [comment]
Same issue here unfortunately :(

**Comment by luchtgitaar** [comment]
+1

**Comment by DCSBL** [comment]
Please just press the 👍 button on the first post if you have this issue.

---

We should adjust https://github.com/DCSBL/python-frank-energie to match the latest changes in the Frank Energie API. Because this is _not documented_ you have to do some magic with looking at the traffic from the app to the server.

I am unable to work on this at the moment, so please feel free to do the above and suggest changes via a PR in this library.

**Comment by DCSBL** [comment]
https://github.com/bajansen/home-assistant-frank_energie/releases/tag/v3.0.0-beta-1

De API was aangepast, vooral rondom het ophalen van gepersonaliseerde data. De API heeft support gekregen voor meerdere 'sites'; Een gebruiker met meerdere huizen/locaties. Toevallig heb ik dat ook dus kon makkelijk testen (Ik ben onlangs verhuist en had overlap, dus ze hebben het via deze methode in hun systeem gezet).

"Works on my machine", zou nice zijn als jullie de beta kunnen testen en/of een code-review te doen in https://github.com/bajansen/home-assistant-frank_energie/pull/103
