### ISSUE TITLE
HA Energy Dashboard and hourly prices

### ISSUE THREAD

**Issue by mcormick** [bajansen/home-assistant-frank_energie#3]
This component records the **current** Frank Energy electricity market and all-in prices. The HA Energy Dashboard calculates electricity usage (and therewith cost) on a per hour basis ... in hindsight, over the past hour. Using the current hourly price would therefore result in incorrect total cost, because that current price is _not yet_ useful. Could you add past-hour prices to the component or do you have an alternative solution?

**Comment by bajansen** [comment]
I can't say I have checked it, but I find it hard to believe the energy dashboard would use the current price to calculate the costs of the hour before opposed to calculating the costs using the value that applied during the respective hour. If not, I think this is something to be fixed in Home Assistant itself, especially seeing the energy dashboard explicitly supports calculating costs based on pricing information stored in a sensor,  and I hardly think this component is the only one providing hourly pricing information.

If I'm thinking about this completely wrong and if this is how the energy dashboard is meant to work, I would appreciate a pointer to other hourly pricing components that do handle this in the manner you suggest.
